meta_product_name: "Vendimo"
meta_title: "Vendimo - Intelligent vending machine solution"
meta_description: "Easily connect outdated vending machines to the internet"
meta_image: "cover.jpg"
twitter_account: "@product_twitter_account"
